### ISSUE TITLE
error downloading eigen

### ISSUE THREAD

**Issue by zanderladd** [jaak-s/macau#13]
Hello,

I am following the steps to install with pip and have all of the dependencies installed but when run pip install . 
I get:
  urllib.error.HTTPError: HTTP Error 403: Forbidden

here is some more of the stack trace:

File "setup.py", line 307, in <module>
      main()
    File "setup.py", line 282, in main
      download_eigen_if_needed(eigen_dest, eigen_url, eigen_inner)
    File "setup.py", line 175, in download_eigen_if_needed
      urlretrieve(url, bzfile)

Happy to provide more information about system configurations etc. but not sure what would help so just let me know. Thanks in advance for your help/time!

**Comment by jaak-s** [comment]
Thanks for the bug report. The Eigen url had become broken.
I've now fixed it and pushed a new version (v0.5.3). Let me know if it works for you.

**Comment by zanderladd** [comment]
yes that fixed it. Thank you!
